package alimentari.entity;

public enum TipoMansione {
	
	ROLE_DIRETTORE,
    ROLE_CASSIERE,
    ROLE_MANAGER,
    ROLE_PULIZIA,
    ROLE_RESPONSABILE,
    ROLE_MAGAZZINIERE_SCAFFALE,
    ROLE_MAGAZZINIERE_BANCO;
	
}
